# Generated by Django 3.2 on 2024-12-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Web Terminal',
                'permissions': [('terminal_connect', 'Can Use Web Terminal'), ('terminal_file', 'Can Edit Files')],
            },
        ),
    ]
